#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Jalagam")]
public partial class DcjalagamDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertVideo_Gallery(Video_Gallery instance);
  partial void UpdateVideo_Gallery(Video_Gallery instance);
  partial void DeleteVideo_Gallery(Video_Gallery instance);
  partial void InsertTest_Driving_Det(Test_Driving_Det instance);
  partial void UpdateTest_Driving_Det(Test_Driving_Det instance);
  partial void DeleteTest_Driving_Det(Test_Driving_Det instance);
  partial void InsertDealer_Registration(Dealer_Registration instance);
  partial void UpdateDealer_Registration(Dealer_Registration instance);
  partial void DeleteDealer_Registration(Dealer_Registration instance);
  partial void InsertPhoto_Gallery_Image_Det(Photo_Gallery_Image_Det instance);
  partial void UpdatePhoto_Gallery_Image_Det(Photo_Gallery_Image_Det instance);
  partial void DeletePhoto_Gallery_Image_Det(Photo_Gallery_Image_Det instance);
  partial void InsertPhoto_Gallery(Photo_Gallery instance);
  partial void UpdatePhoto_Gallery(Photo_Gallery instance);
  partial void DeletePhoto_Gallery(Photo_Gallery instance);
  partial void InsertAccessories_Master(Accessories_Master instance);
  partial void UpdateAccessories_Master(Accessories_Master instance);
  partial void DeleteAccessories_Master(Accessories_Master instance);
  partial void InsertProduct_Master(Product_Master instance);
  partial void UpdateProduct_Master(Product_Master instance);
  partial void DeleteProduct_Master(Product_Master instance);
  partial void InsertBranch_Detail(Branch_Detail instance);
  partial void UpdateBranch_Detail(Branch_Detail instance);
  partial void DeleteBranch_Detail(Branch_Detail instance);
  partial void InsertContact_Us(Contact_Us instance);
  partial void UpdateContact_Us(Contact_Us instance);
  partial void DeleteContact_Us(Contact_Us instance);
  #endregion
	
	public DcjalagamDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JalagamConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DcjalagamDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DcjalagamDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DcjalagamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DcjalagamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Video_Gallery> Video_Galleries
	{
		get
		{
			return this.GetTable<Video_Gallery>();
		}
	}
	
	public System.Data.Linq.Table<Test_Driving_Det> Test_Driving_Dets
	{
		get
		{
			return this.GetTable<Test_Driving_Det>();
		}
	}
	
	public System.Data.Linq.Table<Dealer_Registration> Dealer_Registrations
	{
		get
		{
			return this.GetTable<Dealer_Registration>();
		}
	}
	
	public System.Data.Linq.Table<Photo_Gallery_Image_Det> Photo_Gallery_Image_Dets
	{
		get
		{
			return this.GetTable<Photo_Gallery_Image_Det>();
		}
	}
	
	public System.Data.Linq.Table<Photo_Gallery> Photo_Galleries
	{
		get
		{
			return this.GetTable<Photo_Gallery>();
		}
	}
	
	public System.Data.Linq.Table<Accessories_Master> Accessories_Masters
	{
		get
		{
			return this.GetTable<Accessories_Master>();
		}
	}
	
	public System.Data.Linq.Table<Product_Master> Product_Masters
	{
		get
		{
			return this.GetTable<Product_Master>();
		}
	}
	
	public System.Data.Linq.Table<Branch_Detail> Branch_Details
	{
		get
		{
			return this.GetTable<Branch_Detail>();
		}
	}
	
	public System.Data.Linq.Table<Contact_Us> Contact_Us
	{
		get
		{
			return this.GetTable<Contact_Us>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Video_Gallery")]
public partial class Video_Gallery : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Caption;
	
	private System.DateTime _CreatedDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnCaptionChanging(string value);
    partial void OnCaptionChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    #endregion
	
	public Video_Gallery()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(10,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
	public string Caption
	{
		get
		{
			return this._Caption;
		}
		set
		{
			if ((this._Caption != value))
			{
				this.OnCaptionChanging(value);
				this.SendPropertyChanging();
				this._Caption = value;
				this.SendPropertyChanged("Caption");
				this.OnCaptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Test_Driving_Det")]
public partial class Test_Driving_Det : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Name;
	
	private string _Address;
	
	private string _ContactNo;
	
	private string _EmailId;
	
	private string _ProductCode;
	
	private System.DateTime _CreateDate;
	
	private EntityRef<Product_Master> _Product_Master;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnProductCodeChanging(string value);
    partial void OnProductCodeChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
	
	public Test_Driving_Det()
	{
		this._Product_Master = default(EntityRef<Product_Master>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(7,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string ContactNo
	{
		get
		{
			return this._ContactNo;
		}
		set
		{
			if ((this._ContactNo != value))
			{
				this.OnContactNoChanging(value);
				this.SendPropertyChanging();
				this._ContactNo = value;
				this.SendPropertyChanged("ContactNo");
				this.OnContactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string EmailId
	{
		get
		{
			return this._EmailId;
		}
		set
		{
			if ((this._EmailId != value))
			{
				this.OnEmailIdChanging(value);
				this.SendPropertyChanging();
				this._EmailId = value;
				this.SendPropertyChanged("EmailId");
				this.OnEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string ProductCode
	{
		get
		{
			return this._ProductCode;
		}
		set
		{
			if ((this._ProductCode != value))
			{
				if (this._Product_Master.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnProductCodeChanging(value);
				this.SendPropertyChanging();
				this._ProductCode = value;
				this.SendPropertyChanged("ProductCode");
				this.OnProductCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="Date NOT NULL")]
	public System.DateTime CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Master_Test_Driving_Det", Storage="_Product_Master", ThisKey="ProductCode", OtherKey="Prodcut_Code", IsForeignKey=true)]
	public Product_Master Product_Master
	{
		get
		{
			return this._Product_Master.Entity;
		}
		set
		{
			Product_Master previousValue = this._Product_Master.Entity;
			if (((previousValue != value) 
						|| (this._Product_Master.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Product_Master.Entity = null;
					previousValue.Test_Driving_Dets.Remove(this);
				}
				this._Product_Master.Entity = value;
				if ((value != null))
				{
					value.Test_Driving_Dets.Add(this);
					this._ProductCode = value.Prodcut_Code;
				}
				else
				{
					this._ProductCode = default(string);
				}
				this.SendPropertyChanged("Product_Master");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dealer_Registration")]
public partial class Dealer_Registration : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Dealer_Name;
	
	private string _Age;
	
	private string _Qualification;
	
	private string _EmailId;
	
	private string _ContactNo;
	
	private string _City;
	
	private string _Currnet_Business;
	
	private string _FirmName;
	
	private string _Constitution;
	
	private System.DateTime _CreatedDate;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnDealer_NameChanging(string value);
    partial void OnDealer_NameChanged();
    partial void OnAgeChanging(string value);
    partial void OnAgeChanged();
    partial void OnQualificationChanging(string value);
    partial void OnQualificationChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCurrnet_BusinessChanging(string value);
    partial void OnCurrnet_BusinessChanged();
    partial void OnFirmNameChanging(string value);
    partial void OnFirmNameChanged();
    partial void OnConstitutionChanging(string value);
    partial void OnConstitutionChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public Dealer_Registration()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(4,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dealer_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Dealer_Name
	{
		get
		{
			return this._Dealer_Name;
		}
		set
		{
			if ((this._Dealer_Name != value))
			{
				this.OnDealer_NameChanging(value);
				this.SendPropertyChanging();
				this._Dealer_Name = value;
				this.SendPropertyChanged("Dealer_Name");
				this.OnDealer_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Age
	{
		get
		{
			return this._Age;
		}
		set
		{
			if ((this._Age != value))
			{
				this.OnAgeChanging(value);
				this.SendPropertyChanging();
				this._Age = value;
				this.SendPropertyChanged("Age");
				this.OnAgeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualification", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Qualification
	{
		get
		{
			return this._Qualification;
		}
		set
		{
			if ((this._Qualification != value))
			{
				this.OnQualificationChanging(value);
				this.SendPropertyChanging();
				this._Qualification = value;
				this.SendPropertyChanged("Qualification");
				this.OnQualificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string EmailId
	{
		get
		{
			return this._EmailId;
		}
		set
		{
			if ((this._EmailId != value))
			{
				this.OnEmailIdChanging(value);
				this.SendPropertyChanging();
				this._EmailId = value;
				this.SendPropertyChanged("EmailId");
				this.OnEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string ContactNo
	{
		get
		{
			return this._ContactNo;
		}
		set
		{
			if ((this._ContactNo != value))
			{
				this.OnContactNoChanging(value);
				this.SendPropertyChanging();
				this._ContactNo = value;
				this.SendPropertyChanged("ContactNo");
				this.OnContactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currnet_Business", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Currnet_Business
	{
		get
		{
			return this._Currnet_Business;
		}
		set
		{
			if ((this._Currnet_Business != value))
			{
				this.OnCurrnet_BusinessChanging(value);
				this.SendPropertyChanging();
				this._Currnet_Business = value;
				this.SendPropertyChanged("Currnet_Business");
				this.OnCurrnet_BusinessChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string FirmName
	{
		get
		{
			return this._FirmName;
		}
		set
		{
			if ((this._FirmName != value))
			{
				this.OnFirmNameChanging(value);
				this.SendPropertyChanging();
				this._FirmName = value;
				this.SendPropertyChanged("FirmName");
				this.OnFirmNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Constitution", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Constitution
	{
		get
		{
			return this._Constitution;
		}
		set
		{
			if ((this._Constitution != value))
			{
				this.OnConstitutionChanging(value);
				this.SendPropertyChanging();
				this._Constitution = value;
				this.SendPropertyChanged("Constitution");
				this.OnConstitutionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date NOT NULL")]
	public System.DateTime CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Photo_Gallery_Image_Det")]
public partial class Photo_Gallery_Image_Det : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _PhotoId;
	
	private decimal _GalleryId;
	
	private System.Data.Linq.Binary _Photo;
	
	private EntityRef<Photo_Gallery> _Photo_Gallery;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhotoIdChanging(decimal value);
    partial void OnPhotoIdChanged();
    partial void OnGalleryIdChanging(decimal value);
    partial void OnGalleryIdChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    #endregion
	
	public Photo_Gallery_Image_Det()
	{
		this._Photo_Gallery = default(EntityRef<Photo_Gallery>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal PhotoId
	{
		get
		{
			return this._PhotoId;
		}
		set
		{
			if ((this._PhotoId != value))
			{
				this.OnPhotoIdChanging(value);
				this.SendPropertyChanging();
				this._PhotoId = value;
				this.SendPropertyChanged("PhotoId");
				this.OnPhotoIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryId", DbType="Decimal(6,0) NOT NULL")]
	public decimal GalleryId
	{
		get
		{
			return this._GalleryId;
		}
		set
		{
			if ((this._GalleryId != value))
			{
				if (this._Photo_Gallery.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnGalleryIdChanging(value);
				this.SendPropertyChanging();
				this._GalleryId = value;
				this.SendPropertyChanged("GalleryId");
				this.OnGalleryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Photo
	{
		get
		{
			return this._Photo;
		}
		set
		{
			if ((this._Photo != value))
			{
				this.OnPhotoChanging(value);
				this.SendPropertyChanging();
				this._Photo = value;
				this.SendPropertyChanged("Photo");
				this.OnPhotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Photo_Gallery_Photo_Gallery_Image_Det", Storage="_Photo_Gallery", ThisKey="GalleryId", OtherKey="Id", IsForeignKey=true)]
	public Photo_Gallery Photo_Gallery
	{
		get
		{
			return this._Photo_Gallery.Entity;
		}
		set
		{
			Photo_Gallery previousValue = this._Photo_Gallery.Entity;
			if (((previousValue != value) 
						|| (this._Photo_Gallery.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Photo_Gallery.Entity = null;
					previousValue.Photo_Gallery_Image_Dets.Remove(this);
				}
				this._Photo_Gallery.Entity = value;
				if ((value != null))
				{
					value.Photo_Gallery_Image_Dets.Add(this);
					this._GalleryId = value.Id;
				}
				else
				{
					this._GalleryId = default(decimal);
				}
				this.SendPropertyChanged("Photo_Gallery");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Photo_Gallery")]
public partial class Photo_Gallery : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Caption;
	
	private System.DateTime _CreatedDate;
	
	private EntitySet<Photo_Gallery_Image_Det> _Photo_Gallery_Image_Dets;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnCaptionChanging(string value);
    partial void OnCaptionChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    #endregion
	
	public Photo_Gallery()
	{
		this._Photo_Gallery_Image_Dets = new EntitySet<Photo_Gallery_Image_Det>(new Action<Photo_Gallery_Image_Det>(this.attach_Photo_Gallery_Image_Dets), new Action<Photo_Gallery_Image_Det>(this.detach_Photo_Gallery_Image_Dets));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(6,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Caption
	{
		get
		{
			return this._Caption;
		}
		set
		{
			if ((this._Caption != value))
			{
				this.OnCaptionChanging(value);
				this.SendPropertyChanging();
				this._Caption = value;
				this.SendPropertyChanged("Caption");
				this.OnCaptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date NOT NULL")]
	public System.DateTime CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Photo_Gallery_Photo_Gallery_Image_Det", Storage="_Photo_Gallery_Image_Dets", ThisKey="Id", OtherKey="GalleryId")]
	public EntitySet<Photo_Gallery_Image_Det> Photo_Gallery_Image_Dets
	{
		get
		{
			return this._Photo_Gallery_Image_Dets;
		}
		set
		{
			this._Photo_Gallery_Image_Dets.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Photo_Gallery_Image_Dets(Photo_Gallery_Image_Det entity)
	{
		this.SendPropertyChanging();
		entity.Photo_Gallery = this;
	}
	
	private void detach_Photo_Gallery_Image_Dets(Photo_Gallery_Image_Det entity)
	{
		this.SendPropertyChanging();
		entity.Photo_Gallery = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accessories_Master")]
public partial class Accessories_Master : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Accessorie_Name;
	
	private string _Product_Code;
	
	private string _Price;
	
	private string _About_Product;
	
	private string _Description;
	
	private System.Data.Linq.Binary _DisplayImage;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnAccessorie_NameChanging(string value);
    partial void OnAccessorie_NameChanged();
    partial void OnProduct_CodeChanging(string value);
    partial void OnProduct_CodeChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnAbout_ProductChanging(string value);
    partial void OnAbout_ProductChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDisplayImageChanging(System.Data.Linq.Binary value);
    partial void OnDisplayImageChanged();
    #endregion
	
	public Accessories_Master()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Decimal(6,0) NOT NULL IDENTITY", IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accessorie_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Accessorie_Name
	{
		get
		{
			return this._Accessorie_Name;
		}
		set
		{
			if ((this._Accessorie_Name != value))
			{
				this.OnAccessorie_NameChanging(value);
				this.SendPropertyChanging();
				this._Accessorie_Name = value;
				this.SendPropertyChanged("Accessorie_Name");
				this.OnAccessorie_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Product_Code
	{
		get
		{
			return this._Product_Code;
		}
		set
		{
			if ((this._Product_Code != value))
			{
				this.OnProduct_CodeChanging(value);
				this.SendPropertyChanging();
				this._Product_Code = value;
				this.SendPropertyChanged("Product_Code");
				this.OnProduct_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_About_Product", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string About_Product
	{
		get
		{
			return this._About_Product;
		}
		set
		{
			if ((this._About_Product != value))
			{
				this.OnAbout_ProductChanging(value);
				this.SendPropertyChanging();
				this._About_Product = value;
				this.SendPropertyChanged("About_Product");
				this.OnAbout_ProductChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayImage", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary DisplayImage
	{
		get
		{
			return this._DisplayImage;
		}
		set
		{
			if ((this._DisplayImage != value))
			{
				this.OnDisplayImageChanging(value);
				this.SendPropertyChanging();
				this._DisplayImage = value;
				this.SendPropertyChanged("DisplayImage");
				this.OnDisplayImageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Master")]
public partial class Product_Master : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Prodcut_Code;
	
	private string _Price;
	
	private string _ProductName;
	
	private string _BatteryType;
	
	private string _Color;
	
	private string _Description;
	
	private string _Tags;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private string _CreatedBy;
	
	private System.Data.Linq.Binary _DisplayImage;
	
	private string _Visible;
	
	private EntitySet<Test_Driving_Det> _Test_Driving_Dets;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnProdcut_CodeChanging(string value);
    partial void OnProdcut_CodeChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnBatteryTypeChanging(string value);
    partial void OnBatteryTypeChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnDisplayImageChanging(System.Data.Linq.Binary value);
    partial void OnDisplayImageChanged();
    partial void OnVisibleChanging(string value);
    partial void OnVisibleChanged();
    #endregion
	
	public Product_Master()
	{
		this._Test_Driving_Dets = new EntitySet<Test_Driving_Det>(new Action<Test_Driving_Det>(this.attach_Test_Driving_Dets), new Action<Test_Driving_Det>(this.detach_Test_Driving_Dets));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Decimal(5,0) NOT NULL IDENTITY", IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prodcut_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Prodcut_Code
	{
		get
		{
			return this._Prodcut_Code;
		}
		set
		{
			if ((this._Prodcut_Code != value))
			{
				this.OnProdcut_CodeChanging(value);
				this.SendPropertyChanging();
				this._Prodcut_Code = value;
				this.SendPropertyChanged("Prodcut_Code");
				this.OnProdcut_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
	public string Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatteryType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string BatteryType
	{
		get
		{
			return this._BatteryType;
		}
		set
		{
			if ((this._BatteryType != value))
			{
				this.OnBatteryTypeChanging(value);
				this.SendPropertyChanging();
				this._BatteryType = value;
				this.SendPropertyChanged("BatteryType");
				this.OnBatteryTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Color
	{
		get
		{
			return this._Color;
		}
		set
		{
			if ((this._Color != value))
			{
				this.OnColorChanging(value);
				this.SendPropertyChanging();
				this._Color = value;
				this.SendPropertyChanged("Color");
				this.OnColorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="VarChar(100)")]
	public string Tags
	{
		get
		{
			return this._Tags;
		}
		set
		{
			if ((this._Tags != value))
			{
				this.OnTagsChanging(value);
				this.SendPropertyChanging();
				this._Tags = value;
				this.SendPropertyChanged("Tags");
				this.OnTagsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="Date")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayImage", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary DisplayImage
	{
		get
		{
			return this._DisplayImage;
		}
		set
		{
			if ((this._DisplayImage != value))
			{
				this.OnDisplayImageChanging(value);
				this.SendPropertyChanging();
				this._DisplayImage = value;
				this.SendPropertyChanged("DisplayImage");
				this.OnDisplayImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="VarChar(10)")]
	public string Visible
	{
		get
		{
			return this._Visible;
		}
		set
		{
			if ((this._Visible != value))
			{
				this.OnVisibleChanging(value);
				this.SendPropertyChanging();
				this._Visible = value;
				this.SendPropertyChanged("Visible");
				this.OnVisibleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Master_Test_Driving_Det", Storage="_Test_Driving_Dets", ThisKey="Prodcut_Code", OtherKey="ProductCode")]
	public EntitySet<Test_Driving_Det> Test_Driving_Dets
	{
		get
		{
			return this._Test_Driving_Dets;
		}
		set
		{
			this._Test_Driving_Dets.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Test_Driving_Dets(Test_Driving_Det entity)
	{
		this.SendPropertyChanging();
		entity.Product_Master = this;
	}
	
	private void detach_Test_Driving_Dets(Test_Driving_Det entity)
	{
		this.SendPropertyChanging();
		entity.Product_Master = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Branch_Details")]
public partial class Branch_Detail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Branch_Id;
	
	private string _Branch_Name;
	
	private string _Address;
	
	private string _ContactNumbers;
	
	private string _EmailId;
	
	private System.DateTime _CreatedDate;
	
	private string _Status;
	
	private string _State;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBranch_IdChanging(decimal value);
    partial void OnBranch_IdChanged();
    partial void OnBranch_NameChanging(string value);
    partial void OnBranch_NameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnContactNumbersChanging(string value);
    partial void OnContactNumbersChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    #endregion
	
	public Branch_Detail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(4,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Branch_Id
	{
		get
		{
			return this._Branch_Id;
		}
		set
		{
			if ((this._Branch_Id != value))
			{
				this.OnBranch_IdChanging(value);
				this.SendPropertyChanging();
				this._Branch_Id = value;
				this.SendPropertyChanged("Branch_Id");
				this.OnBranch_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Branch_Name
	{
		get
		{
			return this._Branch_Name;
		}
		set
		{
			if ((this._Branch_Name != value))
			{
				this.OnBranch_NameChanging(value);
				this.SendPropertyChanging();
				this._Branch_Name = value;
				this.SendPropertyChanged("Branch_Name");
				this.OnBranch_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumbers", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string ContactNumbers
	{
		get
		{
			return this._ContactNumbers;
		}
		set
		{
			if ((this._ContactNumbers != value))
			{
				this.OnContactNumbersChanging(value);
				this.SendPropertyChanging();
				this._ContactNumbers = value;
				this.SendPropertyChanged("ContactNumbers");
				this.OnContactNumbersChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string EmailId
	{
		get
		{
			return this._EmailId;
		}
		set
		{
			if ((this._EmailId != value))
			{
				this.OnEmailIdChanging(value);
				this.SendPropertyChanging();
				this._EmailId = value;
				this.SendPropertyChanged("EmailId");
				this.OnEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date NOT NULL")]
	public System.DateTime CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact_Us")]
public partial class Contact_Us : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Id;
	
	private string _Name;
	
	private string _EmailId;
	
	private string _Description;
	
	private string _ContactNumber;
	
	private System.Nullable<System.DateTime> _CreatedDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    #endregion
	
	public Contact_Us()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(10,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="VarChar(200)")]
	public string EmailId
	{
		get
		{
			return this._EmailId;
		}
		set
		{
			if ((this._EmailId != value))
			{
				this.OnEmailIdChanging(value);
				this.SendPropertyChanging();
				this._EmailId = value;
				this.SendPropertyChanged("EmailId");
				this.OnEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="VarChar(13)")]
	public string ContactNumber
	{
		get
		{
			return this._ContactNumber;
		}
		set
		{
			if ((this._ContactNumber != value))
			{
				this.OnContactNumberChanging(value);
				this.SendPropertyChanging();
				this._ContactNumber = value;
				this.SendPropertyChanged("ContactNumber");
				this.OnContactNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
